spring.application.name=BogotaMetroApp
# Swagger UI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha




app.security.jwt-key=${JWT_KEY}
app.security.token-expiration=${HORAS_VALIDEZ}

app.firebase.api-key=${FIREBASE_API_KEY}
app.firebase.auth-domain=${FIREBASE_AUTH_DOMAIN}
app.firebase.app-id=${APP_ID_FIREBASE}

#Configuración de la base de datos
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuración de redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=60000

# Prefijo para las claves de Redis
app.redis.key-prefix=${REDIS_KEY_PREFIX}
app.redis.timeout-seconds=${REDIS_TIMEOUT_SECONDS}
# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Info de la API
springdoc.info.title=BogotaMetro API
springdoc.info.description=API REST para gestión del sistema de metro de Bogotá
springdoc.info.version=1.0.0
springdoc.info.contact.name=SENA
springdoc.info.contact.email=soporte@bogotametro.com